### ISSUE TITLE
Bug - unrendered raw css displaying on 404 "Go back" button

### ISSUE THREAD

**Issue by isaacpearl** [makerdao/community-portal#150]
@MaximumCrash 

## Bug description
When I click "Go back" on a 404 page, the raw text for the previous page's css displays in the rendered page for a few brief frames, rendering as expected a moment later.

## Steps to replicate:
1. Merge PR #149 OR ```git checkout isaac/404``` to have access to 404 pages with a working "Go back" button. (if #149 is already merged, ignore this step)
2. ```yarn build```
3. ```yarn serve``` 
4. Navigate to any valid URI on the built site (```http://localhost:9000/```)
5. Navigate to an invalid URI in the same window/tab
6. Click the 404 page's "Go back" button.
7. You should see the css text flash on screen for a moment:
<img width="1792" alt="Screen Shot 2020-07-12 at 7 00 17 PM" src="https://user-images.githubusercontent.com/21342523/87266839-2e58d900-c494-11ea-9fd6-326184f5278f.png">

**Comment by MaximumCrash** [comment]
From what I can tell so far, the code stays when in development mode, but flashes in production mode. 

I believe this can be fixed with some gatsby-ssr tweaks that we experienced with the Transparancy Dashboard [here](https://github.com/makerdao/commdev-grants-transparency-dashboard/pull/44). (thanks @amy-jung for reminding me 😂 )

**Comment by MaximumCrash** [comment]
Closed by #153 but there are still unfavorable flashing issues in the app. Best to wait until other optimizations are performed prior to this.
