### ISSUE TITLE
Page heading - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#155]
[Page Heading](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1577%3A1720)

![Screen Shot 2020-07-14 at 2 26 35 PM](https://user-images.githubusercontent.com/59940380/87462493-070e2300-c5de-11ea-9db5-e662caa370a2.png)

![Screen Shot 2020-07-14 at 2 26 45 PM](https://user-images.githubusercontent.com/59940380/87462507-0c6b6d80-c5de-11ea-961a-5e73d91c43a3.png)

**Comment by MaximumCrash** [comment]
@shea-fitz just so you know this isn't a component, but more of how someone writes their file. I'll mark this ticket as documentation for that sake. 

This is because the "page heading" is really just:

# A long heading that is multiple lines long

## We've come up with a process for taking notes at a governance and risk meeting to ensure accuracy, readability and consistency. Here's how it goes. 

at the top of one of our files.

**Comment by MaximumCrash** [comment]
Closed by #217
