### ISSUE TITLE
Component - Checklist

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#23]
Especially hackathons and grants, there is a multi step process. To help applicants along, an articulated checklist is a better experience than bullet points. 

[Figma frame](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=294%3A126)

**Comment by MaximumCrash** [comment]
@befitsandpiper 

This Checklist component is meant to be non-functional, as in there's no state you don't actually check anything off, so no need for a form here. 

Do not trust the props provided in the Components documentation as the end all be all. They're simply meant to be for reference. Similarly because components in the specs have a habit of **not matching the documentation**, trust what you see on the Figma design pages (specifically what you see [here](figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=398%3A388)) and cross reference to the best of your ability. When in doubt, ask and I'll make the final call.

Acceptance criteria will be:

1. I should be able to script this component in MDX with as little friction to remember as possible. This means that each child that MDX sees should be the equivalent of 1 checkbox. 

For example, each element in here between line breaks are automatically recognized by MDX as an individual child when its pulled into the Checklist component. Code this in a way that **each** child is it's own checkbox. (For a good example of this practice see me List/Process components. 


**NOTE: Mind the gaps. MDX is picky about line breaks (similarly to MD) on how it recognizes individual children. Notice the line break at the start and end of the component and in-between children.**
```
<Checklist>

   Checkbox 1

   - Checkbox 2 Very conservative sponsorship requirements (under $5000)
 
   - Checkbox 3 Located or targeted at Asia-Pacific (APAC), Latin America (LATAM), Eastern Europe, ect....

   1. Checkbox 4 Direct connection to talent and hackathon attendees
   
    ### Checkbox 5

    <Box>
      Checkbox 6
    </Box>

</Checklist>
```

2. No margin top for this component when it comes to spacing around other components.

**Comment by MaximumCrash** [comment]
Work complete by #57
