### ISSUE TITLE
Testing- Application Pages ( Funding/Work with us)

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#367]
### Page Type by Page Type at the [staging site link](https://community-portal-staging.makerfoundation.com/)

[Application Pages Guide](https://www.notion.so/Application-page-example-Development-grants-or-Join-the-translation-team-81eef02069bc47d2879d0c8bdc823d18)

- Self-Assign this ticket corresponding to a group of pages
- Add your name to the `owner` in [content sprint page](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0) to a group of pages. To see action pages only filter the `qa task` column.

Test away!

#### [Work with us/Translations](https://community-portal-staging.makerfoundation.com/en/work_with_us/translations/)

- [x]  phone browser 1 (safari)
- [ ]  phone browser 2 (chrome)
- [ ]  Desktop chrome
- [ ]  Desktop brave

#### Funding/Hackathon sponsorship
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave
#### Funding/Meetup funding
- [ ]  phone browser 1 (safari)
- [ ]  phone browser 2 (chrome)
- [ ]  Desktop chrome
- [ ]  Desktop brave
#### Funding/Community projects
- [ ]  phone browser 1 (safari)
- [ ]  phone browser 2 (chrome)
- [ ]  Desktop chrome
- [ ]  Desktop brave
#### Funding/Development grants/Index
- [ ]  phone browser 1 (safari)
- [ ]  phone browser 2 (chrome)
- [ ]  Desktop chrome
- [ ]  Desktop brave

**Comment by jerrygoldfarb** [comment]
WorkWithUs/TranslationInitiative (landing page)
> On mobile the footer doesn't go all the way over, so there is a strange white bar next to the links at the bottom of the page, where it should be purple all the way across. This does not appear on any of the desktop versions I looked at. 

WorkWithUs/TranslationInitiative/ TranslatorQuickStartGuide
> Lists under 'best practices' and 'getting started' both contain incomplete sentences with periods, can go back and fix this myself, if we want this to be changed. Will wait to do this in case I need to do these other changes; but also, the last sentence, in italics, needs a period. 

WorkWithUs/TranslationInitiative/ EditorQuickStartGuide
> More lists with incomplete sentences. 
> (on mobile) The same weird footer issue where the purple doesn't go fully across the screen, so there is a white verticle at the bottom of the page.

Funding/HackathonSponsorship
> Old content at the bottom of the page is still showing, needs to be moved to the resources folder(?) so it won't be visible.
> On mobile, the last box ('?If you have some insight you'd like to share...') is the same size, color, etc as the 'Development Grants' and 'Hackathon Guide' boxes, and it seems like they should be related to the eye, but obviously they aren't. Perhaps just a change in the background color for differentiation? Or more padding/spacing

Funding/MeetupFunding
> Looks great on desktop, on mobile the numbers relating to amounts of Dai/grant app's are all jumbled together (in verticle, look fine when flipped horizontal), the words themselves just below are also overlapping a bit. 

Funding/Community Projects
> On one mobile browser it's fine, but on the other, the 'Community Projects Process' button is larger than the box it is supposed to be within, the text above wraps to fit and the button just pokes out either side, it is centered though. On the browser it does fit, it goes exactly to the edge of the box. 

Funding/CommunityProjects/ProjectProcess
> more lists with incomplete sentences

Funding/DevelopmentGrants/Apply
> lists with incomplete sentences (again, happy to go back and fix these if that's what we want)

**Comment by twblack88** [comment]
@jerrygoldfarb thanks for all those notes, if you see a fix you can make, def go for it. @QuintenW93 is our new community member who going to take a pass this weekend when he gets some time .

**Comment by QuintenW93** [comment]
**Hackathon Funding**

> Old content at the bottom of the page is still showing, needs to be moved to the > > resources folder(?) so it won't be visible.
  
Still old content -qw

￼
Line cuts off. Doesn’t reach the bottom of the page. Intentional?
Format is preserved when the page is copied and pasted onto something else.
￼
Some of the text shows up in gray when copied from dark mode. 
￼
Text is more readable in light mode.
￼
Submit application link opens blank URL.￼
Buttons and links should have verbs in text. “Community Chat” should be “chat with us”, “guide to hacking” should be “view guide”. Both links can be “learn more” as calls to action.￼
Changing operating system light to dark mode on my phone does not change the light or dark mode on the site. Not sure if its a bug, planned feature, or unplanned.
<img width="317" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/71051992/93034587-61802b80-f5ef-11ea-9707-64cb982853c8.png">
<img width="570" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/71051992/93034588-6218c200-f5ef-11ea-8549-7c3dcb992466.png">
<img width="542" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/71051992/93034589-6218c200-f5ef-11ea-883a-63bdbbe3ae98.png">
<img width="465" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/71051992/93034590-62b15880-f5ef-11ea-8146-b5a8f065957c.png">
<img width="1440" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/71051992/93034591-62b15880-f5ef-11ea-9a93-a0a9efc3e95f.png">
<img width="545" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/71051992/93034592-6349ef00-f5ef-11ea-8388-5de3475242d4.png">

**Comment by QuintenW93** [comment]
**_WorkWithUS￼_**

There are instances where I try to go to a previous page while using safari, and am sent a blank screen. I am able to get to the “work with us” page only after refreshing.
￼
Potential Typo? Or Intended
￼
Is the “new users” box supposed to lead me somewhere else? It does nothing when clicked.
￼
“New Users” text would be easier to see if purple like the background.
￼
When trying to access the “learn about governance” link , I was sent to another blank page. Had to refresh.
￼
Under “getting started”, clicking on “agenda” and “budget” lead to the 404 message.
￼
<img width="448" alt="image" src="https://user-images.githubusercontent.com/71051992/93284182-f2d5d600-f786-11ea-85d6-b88147f01b5f.png">
<img width="225" alt="image" src="https://user-images.githubusercontent.com/71051992/93284224-06813c80-f787-11ea-9ac2-0ccd544471c9.png">
<img width="513" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/71051992/93284246-11d46800-f787-11ea-94e8-3e4b9c34c8f8.png">
<img width="287" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/71051992/93284250-1567ef00-f787-11ea-844a-3bff594abcaa.png">
<img width="335" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/71051992/93284257-1c8efd00-f787-11ea-8306-125cc2026294.png">
<img width="456" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/71051992/93284268-2284de00-f787-11ea-9a0e-b86bac1db3f8.png">
