### ISSUE TITLE
Testing - Guide Page - Work With us/Funding 

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#370]
[Guide Pages Explanation](https://www.notion.so/Guide-page-example-Work-with-us-Meetups-d611fbbd17264d38981e30f1f48b9655)

- Self-Assign this ticket corresponding to a group of pages
- Add your name to the `owner` in [content sprint page](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0) to a group of pages. To see action pages only filter the `qa task` column.

Test away!

#### Work with us/Content/Writing Style Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Content/Reviewer Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Content/installation guide
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
#### Work with us/Content/Pallette
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
#### Work with us/Content/content-guide
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
#### Work with us/Content/Icons
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
#### Work with us/Content/Visual Style Guide
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
#### Work with us/Meetups/Getting Started Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Meetups/Events Formats Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Meetups/Promotion Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Meetups/Budget Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Hackathons/Guide to Hacking
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Governance and risk meetings/Take notes/Formatting guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Governance and risk meetings/Take notes/Governance call template
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Funding/Development grants/grantee playbook
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2

**Comment by jerrygoldfarb** [comment]
Content/Writing Style Guide: 
On mobile: 'Please note' section, and lists (use&avoid) after, are wrapping after every word, makes the page significantly longer and difficult to read. 

Content sub-pages have changed; installation guide, pallette, icons, visual style guide, are now:
How to Use GitHub **checked**
Hot to Use GitHub For One-off Changes **checked**
How to Use GitHub For Ongoing Work **checked**
> Under # 5 Edit/Add File; 'Create New File' (lower part of this section) there is a broken image, repo shows it as an imgur link

Contributor Tools **checked**
> Green box 'Pro Tips:' is too large on desktop site, too small on mobile (text is coming out of the box on mobile), the 2nd pro tip box on the page is actually fine on mobile browser (for reference) 
( **checked=** at least 2 browsers via desktop and mobile, multiple screens via desktop)


Meetups/Getting Started guide: 
the list (inside the box) under planning&event day: these aren't all sentences, but is it better to leave the periods for ease of reading?

GnR Meetings/TakeNotes/FormattingGuide:
first box with title structure requires scanning left/right exclusively with in the box, which is strange but not necessarily an issue?
especially because the 2nd box scales and is the right size. However it does seem to have some extra parenthesis around it that show up (assume they're meant to be part of the code?)

GnR Meetings/TakeNotes/GovernanceCallNotesTemplate:
Same weird scanning thing with the box of markdown text, again, isn't necessarily an issue just feels kind of abnormal.

GnR Meetings/TakeNotes/NoteTakingProcess
**checked**

Funding/DevelopmentGrants/GranteePlaybook:
list in the box(es), again, are not entirely full sentences, if it's better to change this I'm happy to go back and edit these couple pages with this issue, but if we think it's better for readability that's fine.
