### ISSUE TITLE
Testing- Process Page- Work with Us/ Funding

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#372]
[Process Page Guide](https://www.notion.so/Process-page-example-using-GitHub-ad1e9bdc00214d4aa2fad4e7244d7821)

- Self-Assign this ticket corresponding to a group of pages
- Add your name to the `owner` in [content sprint page](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0) to a group of pages. To see action pages only filter the `qa task` column.

Test away!

#### Work with us/Content/Writing Style Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Content/Reviewer Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Content/installation guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Content/Pallette
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Content/content-guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Content/Icons
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Content/Visual Style Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Meetups/Getting Started Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Meetups/Events Formats Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Meetups/Promotion Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Meetups/Budget Guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Hackathons/Guide to Hacking
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Governance and risk meetings/Take notes/Formatting guide
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Work with us/Governance and risk meetings/Take notes/Governance call template
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2
#### Funding/Development grants/grantee playbook
- [x]  Phone browser 1
- [x]  Phone browser 2
- [x]  Desktop browser 1
- [x]  Desktop browser 2

**Comment by eringeorgen** [comment]
![IMG_3976](https://user-images.githubusercontent.com/70353047/92042993-21d45c80-ed30-11ea-8f9b-5fb61ecd0771.PNG)

Doesn't function in mobile on iphone SE (regardless of browser)

**Comment by eringeorgen** [comment]
Work with us/Content/installation guide - not finding a page named this in the spreadsheet.

**Comment by eringeorgen** [comment]
Work with us/Content/Pallette not found, reviewed Resources/technical-content/Pallette - this page has several broken links which need to be updated.

**Comment by eringeorgen** [comment]
Work with us/Content/content-guide not found, reviewed Resources/technical-content/content-guide -

- Pre-Publication Checklist, styling feedback/suggestion: list is long with lots of space and no bullets, consider adding actual check boxes to specific tasks (so that its more clear what is an item vs a description of the item) or some other styling changes to improve readability.
- Do's &  Don't, styling suggestion: consider putting these side by side in 2 columns for improving visual on desktop
-

**Comment by eringeorgen** [comment]
Work with us/Content/Icons not found, reviewed Resources/technical-content/Icons -

- no icons appear (in any browser)

**Comment by eringeorgen** [comment]
Work with us/Meetups/Getting Started Guide

- All links except feedback form ones are broken/incomplete
- style suggestions: bullet lists have too much internal spacing, Planning list is very long and would benefit from bullets, numbers, or other markers

**Comment by eringeorgen** [comment]
Work with us/Meetups/Events Formats Guide

- styling suggestion, remove excess space within the bullet lists

**Comment by eringeorgen** [comment]
- under "Setting Up An Event Page" heading, styling suggestion: remove subbullets (maybe all bullets?) for this list, but keep the font weight. For example,
"**Name** A good name describes the theme, main topic, or general ethos of the talk."
-additional style suggestion: remove some spacing between bullets within other lists

**Comment by eringeorgen** [comment]
Work with us/Meetups/Budget Guide in the spreadsheet links to Work with us/Meetups/Promotion Guide

**Comment by eringeorgen** [comment]
Work with us/Hackathons/Guide to Hacking
- community chat link is broken
- Styling brackets under "Grants" heading are not functioning

**Comment by eringeorgen** [comment]
Work with us/Governance and risk meetings/Take notes/Formatting guide

- broken code under "Weekly Meeting" , "Password Protection" , "We Also Explore a Rage of Themes" Headings, example
<img width="721" alt="Screen Shot 2020-09-02 at 2 19 49 PM" src="https://user-images.githubusercontent.com/70353047/92037999-8fc85600-ed27-11ea-9e3e-fbbe5c511542.png">
- under "What Happens" heading, styling suggestion: remove spacing between bullets within a list
- under heading "Past Meetings" links are not functioning, styling suggestion: remove subbullets (maybe all bullets?), but keep type weight. For example, "**Transcripts** View transcripts of past meetings"

**Comment by eringeorgen** [comment]
Work with us/Governance and risk meetings/Take notes/Governance call template
- under the heading "Video", styling suggestion: consider putting a sample video that would appear here (?)

**Comment by eringeorgen** [comment]
Funding/Development grants/grantee playbook
- under heading "Social Media Presence", Twitter embed isn't functioning
<img width="502" alt="Screen Shot 2020-09-02 at 2 44 32 PM" src="https://user-images.githubusercontent.com/70353047/92040143-264a4680-ed2b-11ea-9724-879afdfb3df8.png">
-

**Comment by eringeorgen** [comment]
The above comments will be updated after I review the pages in the correct space. Sorry for the confusion.

**Comment by eringeorgen** [comment]
Work with us/Content/Writing Style Guide
- the indent of the first line looks odd here
<img width="269" alt="Screen Shot 2020-09-02 at 3 12 47 PM" src="https://user-images.githubusercontent.com/70353047/92042461-1e8ca100-ed2f-11ea-96e2-ceac619b43d3.png">
<img width="489" alt="Screen Shot 2020-09-02 at 3 07 31 PM" src="https://user-images.githubusercontent.com/70353047/92042463-20566480-ed2f-11ea-9411-fb97ca01d4a9.png">

**Comment by eringeorgen** [comment]
For clarity, the following pages have been moved to resources/technical content/
- Work with us/Content/installation guide 
- Work with us/Content/Pallette
- Work with us/Content/content-guide
- Work with us/Content/Icons
- Work with us/Content/Visual Style Guide

**Comment by eringeorgen** [comment]
General Mobile Menu questions: The mobile menu doesn't allow me to see the dropdown menu items before sending me to the parent page even when I try to just click on the down arrow. Is that the intended result? From a user perspective, it feels like I should be able to open the dropdown menus and click within. At the moment, that is a two step process because it closes the menu when it navigates me to the parent page. Then I must open the mobile menu again (and in some cases scroll down) in order to get to the open dropdown to find the link I am looking for.

**Comment by eringeorgen** [comment]
This comment is a summary of notes that I will flush out with screen shots in additional comments once I've finished reviewing pages:
- On mobile all pages - the left alignment baseline is greater on the left than the right. this compounds a spacing issue that exists on mobile in certain contexts (see additional notes)
- On mobile all pages - there is a general over use of left indents to note hierarchy of information on a page. When added to billuet lists within bullet lists... several pages have text that is very hard to read because of how narrow the text container has become (screen shots to come with links to the specific pages where it's particularly bad or breaking out of the container altogether). I suggest moving the baseline left alignment on mobile more left, removing left indent from baseline bullet point position on desktop and mobile (the bullet already indicates a change in information hierarchy), and removing the indented left alignment of entire paragraphs in relation to their headings (again at least on mobile devices, but the Headings and paragraph type style is already a strong indicator of information hierarchy). This will maximize the available space for text containers throughout the site when on mobile devices.
-  On mobile all pages - the same spacing issues noted with callout boxes (screenshots to come).
