### ISSUE TITLE
Lefthand sidebar moves with accordions

### ISSUE THREAD

**Issue by TomDeMichele** [makerdao/community-portal#421]
**Describe the bug**
The Lefthand Sidebar moves with accordions, at least in certain situations. For example, it happens on this page https://community-portal-staging.makerfoundation.com/en/work_with_us/content/contributor-tools

**To Reproduce**
1. Go to https://community-portal-staging.makerfoundation.com/en/work_with_us/content/contributor-tools
2. Click on any of the accordions at the bottom of the page.
3. Watch sidebar go.

**Expected behavior**
For this not to happen, for the sidebar to stay put.

**Screenshots**
![Screen Shot 2020-09-02 at 3 20 57 PM](https://user-images.githubusercontent.com/54551507/92042969-15e89a80-ed30-11ea-9e3e-b7893923fc48.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Brave
 - Version 1.13.82

**Comment by MaximumCrash** [comment]
@twblack88 @TomDeMichele I've labeled this with wontfix. 

The reason this happens is because the sidenav has `position: sticky`, and when these specific accordions with tons of content open, the page's height is radically increased. This specific bug only happens when the sidebar has reached it's max sticky Y position. (ie. When you scroll and see the footer stop scrolling/sticking). 

Sadly this is an unavoidable annoyance, but the sidenav goes back to normal as soon you scroll. 

Since it looks like I'm going to have to refactor the sidenav, this may also not be an issue soon, since I may move away from using position: sticky due to these situations.

**Comment by MaximumCrash** [comment]
Closed by #441
