### ISSUE TITLE
Relative Links Don't Work

### ISSUE THREAD

**Issue by andytudhope** [makerdao/community-portal#60]
When I put in a relative link (in the cheatsheet for example) to `./intermediate` or to `../engineering/search`, then the site will try and direct me to `https://./intermediate` or `https://../engineering/search`

This should obviously not be the case, and I should be directed to the directory indicated by my, like, relative ways ;)

**Comment by MaximumCrash** [comment]
Ah yeah for relative links you don't need to use dot notation, since it's not based on file directory, but instead based on true url. You can write URLs 3 ways. 

```[Link](/work_with_us/bounties)``` for Internal links (uses current locale)

or 

```[Link](https://makerdao.com)``` for External links

or 

```[link](es/work_with_us/translations)``` for internal locale specific routes. 

This is because our Link component checks whether it's internal/external, if the internal has a locale appened (fr/work_with_us/bounties), or if external links have https (http://google.com will automatically be transformed into https://google.com)

Shorthand is interrnal links are not directory based like images, but route based like how you would expect to type them in your URL. I don't think it would be the best idea to support relatives with the dot notation, only because then you, as a content creator, have to remember file depth, and I as a developer have to support and maintain this logic.
